import json
from pathlib import Path
import base64
from typing import Any, Dict, List
from datetime import datetime

def generate_html_report(run_data: Dict[str, Any], vulnerabilities: List[Dict[str, Any]], history: List[Dict[str, Any]]) -> str:
    """
    Generates a self-contained HTML report for the penetration test run.
    """
    
    # Calculate stats
    critical_count = sum(1 for v in vulnerabilities if v['severity'] == 'critical')
    high_count = sum(1 for v in vulnerabilities if v['severity'] == 'high')
    medium_count = sum(1 for v in vulnerabilities if v['severity'] == 'medium')
    low_count = sum(1 for v in vulnerabilities if v['severity'] == 'low')
    
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Strix Security Report - {run_data.get('run_name', 'Unknown Run')}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&family=JetBrains+Mono:wght@400;600&display=swap');
        body {{ font-family: 'Inter', sans-serif; }}
        .mono {{ font-family: 'JetBrains Mono', monospace; }}
    </style>
</head>
<body class="bg-gray-50 text-gray-900">

    <!-- Header -->
    <div class="bg-slate-900 text-white py-12">
        <div class="max-w-5xl mx-auto px-6">
            <div class="flex justify-between items-center mb-6">
                <h1 class="text-4xl font-bold">Security Assessment Report</h1>
                <div class="text-right opacity-70">
                    <p>Generated by Strix AI</p>
                    <p>{report_date}</p>
                </div>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-6 mt-8 border-t border-slate-700 pt-8">
                <div>
                    <div class="text-slate-400 text-sm uppercase tracking-wider">Target</div>
                    <div class="font-semibold text-lg truncate">{run_data.get('targets', [{'original': 'Unknown'}])[0].get('original')}</div>
                </div>
                 <div>
                    <div class="text-slate-400 text-sm uppercase tracking-wider">Total Findings</div>
                    <div class="font-semibold text-lg">{len(vulnerabilities)}</div>
                </div>
                 <div>
                    <div class="text-slate-400 text-sm uppercase tracking-wider">Duration</div>
                    <div class="font-semibold text-lg">{run_data.get('duration', 'N/A')}s</div>
                </div>
                 <div>
                    <div class="text-slate-400 text-sm uppercase tracking-wider">Status</div>
                    <div class="font-semibold text-lg uppercase text-green-400">Completed</div>
                </div>
            </div>
        </div>
    </div>

    <div class="max-w-5xl mx-auto px-6 py-12">
        
        <!-- Executive Summary -->
        <section class="mb-12">
            <h2 class="text-2xl font-bold mb-6 border-b pb-2">Executive Summary</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                    <h3 class="text-lg font-semibold mb-4">Risk Overview</h3>
                    <div class="space-y-3">
                        <div class="flex items-center justify-between p-3 bg-red-50 rounded border border-red-100">
                            <span class="font-medium text-red-900">Critical</span>
                            <span class="font-bold text-red-600 bg-white px-3 py-1 rounded shadow-sm">{critical_count}</span>
                        </div>
                        <div class="flex items-center justify-between p-3 bg-orange-50 rounded border border-orange-100">
                            <span class="font-medium text-orange-900">High</span>
                            <span class="font-bold text-orange-600 bg-white px-3 py-1 rounded shadow-sm">{high_count}</span>
                        </div>
                         <div class="flex items-center justify-between p-3 bg-yellow-50 rounded border border-yellow-100">
                            <span class="font-medium text-yellow-900">Medium</span>
                            <span class="font-bold text-yellow-600 bg-white px-3 py-1 rounded shadow-sm">{medium_count}</span>
                        </div>
                         <div class="flex items-center justify-between p-3 bg-blue-50 rounded border border-blue-100">
                            <span class="font-medium text-blue-900">Low</span>
                            <span class="font-bold text-blue-600 bg-white px-3 py-1 rounded shadow-sm">{low_count}</span>
                        </div>
                    </div>
                </div>
                <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
                    <h3 class="text-lg font-semibold mb-4">Assessment Scope</h3>
                    <p class="text-gray-600 mb-4">
                        This automated security assessment was conducted using Strix, an autonomous AI security agent. 
                        The agent performed a comprehensive scan including reconnaissance, vulnerability scanning, and 
                        exploitation attempts based on the provided configuration.
                    </p>
                    <div class="text-sm text-gray-500">
                        <strong>Run ID:</strong> {run_data.get('run_id')}
                    </div>
                </div>
            </div>
        </section>

        <!-- Findings -->
        <section class="mb-12">
            <h2 class="text-2xl font-bold mb-6 border-b pb-2">Detailed Findings</h2>
            {_render_findings(vulnerabilities)}
        </section>

        <!-- Audit Log (Screenshots) -->
        <section>
            <h2 class="text-2xl font-bold mb-6 border-b pb-2">Evidence & Audit Log</h2>
            <div class="space-y-6">
                {_render_audit_log(history)}
            </div>
        </section>

    </div>
</body>
</html>
    """
    return html

def _render_findings(vulnerabilities):
    if not vulnerabilities:
        return '<div class="p-6 bg-green-50 text-green-800 rounded text-center">No vulnerabilities were identified during this scan.</div>'
    
    html = '<div class="space-y-6">'
    for v in vulnerabilities:
        colors = {
            'critical': 'border-red-500 bg-red-50',
            'high': 'border-orange-500 bg-orange-50',
            'medium': 'border-yellow-500 bg-yellow-50',
            'low': 'border-blue-500 bg-blue-50'
        }
        color_class = colors.get(v['severity'], 'border-gray-500 bg-gray-50')
        
        html += f"""
        <div class="bg-white rounded-lg shadow-sm border-l-4 {color_class} overflow-hidden">
            <div class="p-6">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-xl font-bold text-gray-900">{v['title']}</h3>
                    <span class="uppercase text-xs font-bold tracking-wider px-2 py-1 rounded bg-white border shadow-sm">{v['severity']}</span>
                </div>
                <div class="prose max-w-none text-gray-700">
                    {v['content'].replace(chr(10), '<br>')}
                </div>
                <div class="mt-4 pt-4 border-t text-xs text-gray-400">
                    Finding ID: {v['id']}
                </div>
            </div>
        </div>
        """
    html += '</div>'
    return html

def _render_audit_log(history):
    html = ""
    # Filter for tools with screenshots
    tools_with_screens = [h for h in history if h.get('type') == 'tool' and h.get('screenshot_url')]
    
    if not tools_with_screens:
        return '<div class="text-gray-500 italic">No visual evidence captured.</div>'

    for item in tools_with_screens:
        # Try to embed image as base64 for portability
        img_src = item['screenshot_url']
        local_path = item.get('local_screenshot_path')
        
        if local_path:
            try:
                path_obj = Path(local_path)
                if path_obj.exists():
                    with open(path_obj, "rb") as f:
                        b64_data = base64.b64encode(f.read()).decode('utf-8')
                        img_src = f"data:image/png;base64,{b64_data}"
            except Exception as e:
                print(f"Error embedding screenshot: {e}")
        
        html += f"""
        <div class="bg-white p-4 rounded shadow-sm border border-gray-200">
            <div class="flex items-center gap-2 mb-2 text-sm font-mono text-purple-600">
                <span>🛠 {item.get('tool_name', 'Unknown Tool')}</span>
                <span class="text-gray-400">| {item.get('timestamp', '')}</span>
            </div>
            <div class="border rounded overflow-hidden bg-gray-100">
                <img src="{img_src}" class="max-w-full h-auto mx-auto" alt="Screenshot evidence">
            </div>
            <div class="mt-2 text-xs text-gray-500 font-mono bg-gray-50 p-2 rounded overflow-x-auto">
                Arguments: {json.dumps(item.get('args', {}))}
            </div>
        </div>
        """
    return html
